### ISSUE TITLE
Property Language issue in store dynamic properties 

### ISSUE THREAD

**Issue by Koshalgarg155** [VirtoCommerce/vc-module-store#109]
HI,
I am facing an issue in the platform store module. I have created dynamic properties with multi-language. So there it is showing 5 languages but it should show only 2 languages one is the primary default language and the other one is the additional language but it's showing 5 languages. I think its some bug so please check this and give a solution

![image](https://user-images.githubusercontent.com/99241542/202196035-ffc27341-94ed-44f0-a123-939897a32210.png)

Thanks

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8233 has been created

**Comment by Dan-BV** [comment]
Hi, @Koshalgarg155 ! 
We apologize for the long response time.
At the moment there are several languages pre-installed in the pure platform, so if you add two, the total number of languages may become five. This is not a bug, and you can remove languages you don't use.
