### ISSUE TITLE
IStoreSearchService.SearchStoresAsync marked as obsolete

### ISSUE THREAD

**Issue by j-mok** [VirtoCommerce/vc-module-store#111]
Why is `IStoreSearchService.SearchStoresAsync()` marked as obsolete and what is the current alternative for service consumers? The comment _"Need to remove after inheriting StoreSearchService from SearchService."_ looks more like a TODO mark rather than a workaround and I couldn't find any documentation regarding this.

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8237 has been created

**Comment by Dan-BV** [comment]
You are right. Please ignore this comment. We will correct it as soon as possible.

**Comment by OlegoO** [comment]
@j-mok Already fixed in https://github.com/VirtoCommerce/vc-module-store/releases/tag/3.400.0 release
