### ISSUE TITLE
Query optimization based on collection emptiness #96

### ISSUE THREAD

**Issue by yecli** [VirtoCommerce/vc-module-store#18]
Need to optimize [`StoreRepositoryImpl.GetStoresByIds`](https://github.com/VirtoCommerce/vc-module-store/blob/dev/VirtoCommerce.StoreModule.Data/Repositories/StoreRepositoryImpl.cs#L106) method the same way as it was done in https://github.com/virtocommerce/vc-module-cart/issues/34.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-store/releases/tag/v2.13.9
