### ISSUE TITLE
Allow searching stores by store state and used FFCs

### ISSUE THREAD

**Issue by avas** [VirtoCommerce/vc-module-store#22]
Changes proposal:
* `StoreServiceImpl` should allow searching stores by store state. This will allow calling site to find stores by state (e.g. to get first available open store or all closed/restricted stores).
* Also, would be nice to search stores by FFCs used by these stores. This way, calling site would be able to get all stores that use given FFCs.

Additional context:
In HOT, we want to optimize the way that storefront fills `WorkContext.AllStores` property, so that it would contain only stores available for user. This task required us to extend store search, so that we would be able to:
* find first available open store;
* find stores that use fulfillment centers available for user.
Right now, we are doing this in our store extension module. But, since state and FFC IDs are added by `vc-module-store`, IMO search by these fields should also be implemented in `vc-module-store`.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-store/releases/tag/v2.13.9
