### ISSUE TITLE
PolymorphicStoreJsonConverter implementation doesn't allow to populate shipping methods which are not directly derived from ShippingMethod

### ISSUE THREAD

**Issue by IvanSalov** [VirtoCommerce/vc-module-store#24]
Hi,

I've created my own custom shipping method class that is supposed to be the base class for all of shipping methods in my solution. Let's name it CustomShippingMethod. It's derived from abstract ShippingMethod class and is abstract as well. It has it's own implementation of rate calculation. I have my own api methods that deals with CustomShippingMethod. But PolymorphicStoreJsonConverter doesn't allow me to populate shipping methods that are derived from my CustomShippingMethod.
It consumes everything that IsAssignable from following types:
`typeof(Store), typeof(SearchCriteria), typeof(PaymentMethod), typeof(ShippingMethod), typeof(TaxProvider)`
But when it tries to populate the instance, then condition is following: 
`else if (objectType == typeof(ShippingMethod))`
so there is no way it can populate shipping methods that are derived from CustomShippingMethod.

**Comment by akak1977** [comment]
Released: https://github.com/VirtoCommerce/vc-module-store/releases/tag/v2.13.10
