### ISSUE TITLE
Cannot select some fulfillment centers on 'Advanced properties' blade when there are more than 100 centers

### ISSUE THREAD

**Issue by artem-dudarev** [VirtoCommerce/vc-module-store#28]
We have more than 100 fulfillment centers, and some centers never get to the `ui-select` because the script loads only first 100 centers and then filters them by keyword instead of passing the keyword to the search API.

VirtoCommerce.Store v2.13.9

**Comment by yecli** [comment]
Released: https://github.com/VirtoCommerce/vc-module-store/releases/tag/v2.13.11
