### ISSUE TITLE
Store details blade: selected catalog appears 2 times in catalogs dropdown

### ISSUE THREAD

**Issue by avas** [VirtoCommerce/vc-module-store#54]
Steps to reproduce:
1. Choose any store with assigned catalog, open its details.
2. Open catalogs dropdown.
3. If needed, scroll through it until the selected catalog will be fetched from the platform.

AR: there are two entries for the selected catalog:
![image](https://user-images.githubusercontent.com/1835759/102971089-4779b180-452b-11eb-84e6-54e7d83a7420.png)

ER: selected catalog should appear only once.

Note: it seems like this bug appeared when [adding infinite scroll](https://github.com/VirtoCommerce/vc-module-store/pull/50/files#diff-11092865df71e28f0af5c21aff77ebb2b812e53cf8586dc5855829a097648875R99-R122) to the catalogs dropdown. The new code pre-fetches selected catalog and then starts fetching catalogs from the platform, but for some reason it does not check if fetched catalogs contain selected catalog (which was already prefetched and added to dropdown) and does not exclude it from fetched catalogs.

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-6477 has been created

**Comment by OlegoO** [comment]
It's expected behaviour. Because the first element is selected, then all elements sorted alphabetically and loaded by demand with pagination.
