### ISSUE TITLE
Add validation for store code

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-module-store#6]
Because of seo reasons and storefront routing, store can't have code with spaces. We need to add client-side & server-side validation to disallow this.

**Comment by tatarincev** [comment]
![image](https://user-images.githubusercontent.com/7566324/34357072-918790c2-ea4c-11e7-9dff-09f1d4c7338f.png)

Allow only letters and numbers and an underscore character.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-store/releases/tag/v2.13.4
